---
  - name: install tools
    apt: name={{ item }} state=present update_cache=yes
    with_items:
     - python-httplib2

  - name: install nginx
    apt: name=nginx state=present update_cache=yes

  - name: configure nginx site
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0755
    with_dict: sites
    notify: restart nginx
  - name: ensure nginx started
    service: name=nginx state=started enabled=yes

  - name: Get active sites
    shell: ls -1 /etc/nginx/sites-enabled
    register: active

  - name: de-activate nginx sites
    file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
    with_items: active.stdout_lines
    when: item not in sites
    notify: restart nginx

  - name: activate demo nginx site
    file: src=/etc/nginx/sites-available/{{ item }}}} dest=/etc/nginx/sites-enabled/{{ item }} state=link
    with_dict: sites
    notify: restart nginx

  - name: ensure nginx started
    service: name=nginx state=started enabled=yes
