---
# tasks file for apache2
  - name: install pyhon dependencies
    apt: name={{item}} state=present
    with_items:
      - python-pip
      - python-virtualenv
      - python-mysqldb
    tags: ['packages']

  - name: copy demo app source
    copy: src=demo/app/ dest=/var/www/demo mode=0755
    notify: restart apache2
    tags: ['configure']

  - name: copy demo app config demo.wsgi
    template: src=demo.wsgi.j2 dest=/var/www/demo/demo.wsgi mode=0755
    notify: restart apache2
    tags: ['configure']

  - name: copy apache virtual host config
    copy: src=files/demo/demo.conf dest=/etc/apache2/sites-available mode=0755
    notify: restart apache2
    tags: ['configure']

  - name: setup python virtualenv
    pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
    notify: restart apache2
    tags: ['system']

  - name: activate demo apache site
    file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link
    notify: restart apache2
    tags: ['configure']
