---
  - hosts: database
    become: true
    roles:
      - role: mysql
        #come from group_vars/all.yml
        db_user_name: "{{ db_user }}"
        db_user_pass: "{{ db_pass }}"
        db_user_host: '%'
